version: '3.9'

services:
  db:
    image: postgres:15
    container_name: k9log_postgres
    restart: always
    environment:
      POSTGRES_USER: k9log_user
      POSTGRES_PASSWORD: k9log_pass
      POSTGRES_DB: k9log_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: k9log_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@k9log.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  web:
    build:
      context: ./backend
    container_name: k9log_backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgdata:
